### ISSUE TITLE
costum_label 

### ISSUE THREAD

**Issue by juloder** [mlfpm/deepof#51]
Hi deepof

I am trying to set up deepof for a multi-animal experiment. I am struggling with the body-part labeling: although I am using the deepof_8 scheme, my body-parts are named differently. Therefore, I created a custom label but I get the following error when I create the project: 

`It seems you're using a custom labeling scheme which is missing key body parts. You can proceed, but not all areas will be computed.```

This is my custom labeling code : 

```
deepof_custom = {
                "nose": ["leftear", "rightear"],
                "midbody": ["leftear", "rightear", "leftside", "rightside", "tailbase"],
                "tailbase": ["tailtip"],
            }
```

and this is my project file: 
```

my_project = deepof.data.Project(
    project_path=r"C:\Users\odejul00\deepof",
    video_path=r"C:\Users\odejul00\deepof\Social_Videos", 
    table_path=r"C:\Users\odejul00\deepof\tables", 
    project_name="my_project", 
video_scale=420,
arena="polygonal-manual",
animal_ids=["individual1", "individual2"],
    bodypart_graph=deepof_custom,
)

```

Also, when I try to run the unsupervised analysis, I get this error: 

```
>>> supervised_annot = my_project.supervised_annotation()
Traceback (most recent call last):
  File "C:\Users\odejul00\.conda\envs\deepof\lib\site-packages\pandas\core\indexes\base.py", line 3802, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 5745, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 5753, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'individual1_Center'
```

Is my custom labeling wrong or do you know why it doesn't apply the defined bodyparts? 
Thank you :)

**Comment by NoCreativeIdeaForGoodUserName** [comment]
Hi juloder,

The things that usually go wrong here are spelling errors in the body part names, not including the animal ids or spelling errors in the ids. It is important that everything is written exactly the same as in the column names of your tables. I did not notice anything obvious in this regard in your example though (but obviously I do not know how your tables look).

Since you got an error during project creation the project is not created correctly, so all downstream issues may be caused by that.  Just from this code alone I cannot see what exactly went wrong, however:

[Here](https://datashare.mpcdf.mpg.de/s/DEbgPN02vwQH1O7) you have an upload link you can use to provide a subset of your video and table files to deepof which would allow me to check where exactly the error originates from (the files will only be visible to us upon upload).

Best regards,
Patrick

**Comment by juloder** [comment]
Hi Patrick 

thank you very much. 
I tried to make sure that the spelling is the same as in the tables, but maybe I missed something. 

I am happy to share some files with you. what is the password? 

Best, 
Julia

**Comment by NoCreativeIdeaForGoodUserName** [comment]
Hi Julia,

It seems that we currently have a problem with the upload folder (you should be able to upload stuff without having to enter any password). Unfortunately I am not the owner of the folder and therefore will have to wait for a colleague to fix it.

If you do not want to wait for that (it should not take too long, but potentially longer than a day), I can offer you to  share the data with me directly instead. My work e-mail is:

patrick_schlegel@psych.mpg.de

Best regards,
Patrick

**Comment by NoCreativeIdeaForGoodUserName** [comment]
Thanks, 

your problem comes from the following:

Since you are using an 8-point-labelling-Scheme some of the downstream processing options will not work. This is why you get the warning message:

`It seems you're using a custom labeling scheme which is missing key body parts. You can proceed, but not all areas will be computed.`

The downstream error when you try to run the first step of the unsupervised analysis comes from the different names of your bodyparts. I suspect you likely executed the function with inputs similar to this:

```
(
    graph_preprocessed_coords,
    adj_matrix,
    to_preprocess,
    global_scaler,
) = my_deepof_project.get_graph_dataset(
    animal_id="individual1",  # Comment out for multi-animal embeddings
    center="Center",
    align="Spine_1",
    window_size=25,
    window_step=1,
    test_videos=1,
    preprocess=True,
    scale="standard",
)
```

However, since the names of your bodyparts are different, you also need to adjust the inputs accordingly. E.g. like this:

```
(
    graph_preprocessed_coords,
    adj_matrix,
    to_preprocess,
    global_scaler,
) = my_deepof_project.get_graph_dataset(
    animal_id="individual1",  # Comment out for multi-animal embeddings
    center="midbody",   #<- changed with your bodypart name
    align="midbody", #<- changed with your bodypart name 
    window_size=25,
    window_step=1,
    test_videos=1,
    preprocess=True,
    scale="standard",
)
```

So always adjust bodypart-names according to your labelling scheme. 

Notice that using an 8-point labelling scheme will cause a bunch of parameters not getting calculated downstream. For instance the huddle annotator in the supervised pipeline will be skipped.

Best regards,
Patrick

For instance the supervised huddle behavior needs a list

**Comment by juloder** [comment]
Hi Patrick 

Thank you for your fast response. After creating the project: 
`my_project = my_project.create(verbose=True)`

I run the following commands: 
```
my_project_coords = my_project.get_coords(center="midbody", polar=False, align="nose", speed=0)
my_project_dists  = my_project.get_distances(speed=0)
my_project_angles = my_project.get_angles(speed=0)
my_project_areas = my_project.get_areas(speed=0)
```

With the adjusted bodyparts. 

If I understand the website correctly, the command that you are showing is 'only' creating the graph of the skeleton (sanity check for further processing) - I adjusted the command and I can plot the graph (see image attached). It detected 2 mice but also a square. Could this be the problem? 

![Figure_1](https://github.com/user-attachments/assets/2ca05e03-6ecf-4c58-bcdb-3d70d962eb39)


When I am trying to run the unsupervised annotation, I still get the same error: 
code: 
`supervised_annot = my_project.supervised_annotation()`

error: 
```
>>> supervised_annot = my_project.supervised_annotation()
Traceback (most recent call last):
  File "C:\Users\odejul00\.conda\envs\deepof\lib\site-packages\pandas\core\indexes\base.py", line 3802, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 5745, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 5753, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'individual1_Center'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\odejul00\.conda\envs\deepof\lib\site-packages\deepof\data.py", line 1765, in supervised_annotation
    coords = self.get_coords(center=center, align=align)
  File "C:\Users\odejul00\.conda\envs\deepof\lib\site-packages\deepof\data.py", line 1124, in get_coords
    value[aid + ("_" if aid != "" else "") + center][coord_1],
  File "C:\Users\odejul00\.conda\envs\deepof\lib\site-packages\pandas\core\frame.py", line 3806, in __getitem__
    return self._getitem_multilevel(key)
  File "C:\Users\odejul00\.conda\envs\deepof\lib\site-packages\pandas\core\frame.py", line 3857, in _getitem_multilevel
    loc = self.columns.get_loc(key)
  File "C:\Users\odejul00\.conda\envs\deepof\lib\site-packages\pandas\core\indexes\multi.py", line 2916, in get_loc
    loc = self._get_level_indexer(key, level=0)
  File "C:\Users\odejul00\.conda\envs\deepof\lib\site-packages\pandas\core\indexes\multi.py", line 3263, in _get_level_indexer
    idx = self._get_loc_single_level_index(level_index, key)
  File "C:\Users\odejul00\.conda\envs\deepof\lib\site-packages\pandas\core\indexes\multi.py", line 2849, in _get_loc_single_level_index
    return level_index.get_loc(key)
  File "C:\Users\odejul00\.conda\envs\deepof\lib\site-packages\pandas\core\indexes\base.py", line 3804, in get_loc
    raise KeyError(key) from err
KeyError: 'individual1_Center'
```

My second question is the following: if the problem is arising from the fact that my custom labeling has 8 bodyparts like the deepof_8, could I add the line 'exclude_bodyparts=[ "Tailtip"] to reduce it to 7 body parts? 

I hope this is clear - thank you very much for your help! 

Best wishes, 
Julia

**Comment by NoCreativeIdeaForGoodUserName** [comment]
Hi,

Yes, first the get_graph_dataset function creates a few things, among others a matrix containing the connected body parts (this is what you plotted here) and a preprocessed block of data that can then be later used for the unsupervised learning pipeline. 

That it plots both mice + this square is weird. Are you sure that you included the animal id in the command (as animal_id="individual1"?

Try the following commands in a clean environment:

```
import copy
import os
import numpy as np
import pickle
import deepof.data
```

```
from IPython import display
from networkx import Graph, draw
import deepof.visuals
import matplotlib.pyplot as plt
import seaborn as sns
```

```
deepof_custom = {
                "nose": ["leftear", "rightear"],
                "midbody": ["leftear", "rightear", "leftside", "rightside", "tailbase"],
                "tailbase": ["tailtip"],
            }
```

```
my_deepof_project = deepof.data.Project(
    project_path=os.path.join("[your_folder_name]"), 
    video_path=os.path.join("[your_video_folder_name]"),
    table_path=os.path.join("[your_table_folder_name]"),
    project_name="[your_project_name",
    arena="polygonal-manual",
    animal_ids=["individual1", "individual2"],
    video_format=".mp4",
    bodypart_graph=deepof_custom,  # Can also be set to 'deepof_14' (default), or 'deepof_8'
    video_scale=380,
    iterative_imputation="partial",
    smooth_alpha=1,
    exp_conditions=None,
)
```

```
my_deepof_project = my_deepof_project.create(force=True)
```

```
(
    graph_preprocessed_coords,
    adj_matrix,
    to_preprocess,
    global_scaler,
) = my_deepof_project.get_graph_dataset(
    animal_id="individual1",  # Comment out for multi-animal embeddings
    center="midbody",
    align="midbody",
    window_size=25,
    window_step=1,
    test_videos=1,
    preprocess=True,
    scale="standard",
)
```

```
plt.figure(figsize=(3, 3))
draw(Graph(adj_matrix))
plt.show()
```

This should result in a graph plot of only one of your mice. From there on you than then train an unsupervised model, if this is what you want to do. For starters the supervised pipeline may be a little bit more interesting for you though.

**Comment by juloder** [comment]
I run the commands for individual 1and now there is just one mouse on the graph. However, when I run the supervised (sorry, misspelled it before) annotation, I get the same error (KeyError: 'individual1_Center'). I don't understand why it is not keeping the custom label? 

Do you think I can change the bodyparts in my DLC files to the same labeling as the deepof_8? I don't know yet how such a code would look like but maybe it is easier to change these labels? 

Just for me to know: 
Are these commands important or not? 
```
my_project_coords = my_project.get_coords(center="midbody", polar=False, align="nose", speed=0)
my_project_dists  = my_project.get_distances(speed=0)
my_project_angles = my_project.get_angles(speed=0)
my_project_areas = my_project.get_areas(speed=0)
```
Thank you so much for your help! 
Best, 
Julia

**Comment by NoCreativeIdeaForGoodUserName** [comment]
Hi Julia,

The supervised annotation has optional input arguments that would allow you to rename the names of the bodypart that represents the center to the one you use (similar for the align default that is Spine_1). 

```
    def supervised_annotation(
        self,
        params: Dict = {},
        center: str = "Center",
        align: str = "Spine_1",
        video_output: bool = False,
        frame_limit: int = np.inf,
        debug: bool = False,
        n_jobs: int = 1,
        propagate_labels: bool = False,
    ) -> table_dict:
```

However, before you can call the supervised annotation you first would have to load a csv file that contains your grouping data (which mice were part of which experiment e.g. control and stress etc.)

In general you also can just change the column names in your tables which would mean that you can skip adding the renamed labels as additional input information.

Best regards,
Patrick

**Comment by juloder** [comment]
Hi Patrick 
I have added the experimental conditions. For the code that you send in your last comment: I know I have to change 'center' to midbody, but how else would I need to complete the code? 

Thank you very much :)

**Comment by NoCreativeIdeaForGoodUserName** [comment]
I just checked again and unfortunately some of the bodypart names in the supervised annotations remain hardcoded. To really use everything you would have to rename the table column headers to match the bodypart names that deepof uses. You could do that with a relatively simple script. The "correct" names would be the same ones you can find in the deepof_8 bodypart graph:

```
"deepof_8": {
    "Nose": ["Left_ear", "Right_ear"],
    "Center": [
        "Left_fhip",
        "Right_fhip",
        "Tail_base",
        "Left_ear",
        "Right_ear",
    ],
    "Tail_base": ["Tail_tip"],
},
```

so nose -> Nose, midbody -> Center etc.

I just added updating that section to also fully work with custom graphs to my to-do list.

**Comment by juloder** [comment]
Hi Patrick 
I've changed now the bodypart labeling to deepof_8. Unfortunately, when I create the project I get the following error now: 

```
>>> my_project = my_project.create(force=True)
Setting up project directories...
Loading trajectories...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\odejul00\.conda\envs\deepof\lib\site-packages\deepof\data.py", line 782, in create
    tables, quality = self.load_tables(verbose)
  File "C:\Users\odejul00\.conda\envs\deepof\lib\site-packages\deepof\data.py", line 416, in load_tables
    tab_copy = tab_copy.iloc[2:].astype(float)
  File "C:\Users\odejul00\.conda\envs\deepof\lib\site-packages\pandas\core\generic.py", line 6240, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
  File "C:\Users\odejul00\.conda\envs\deepof\lib\site-packages\pandas\core\internals\managers.py", line 448, in astype
    return self.apply("astype", dtype=dtype, copy=copy, errors=errors)
  File "C:\Users\odejul00\.conda\envs\deepof\lib\site-packages\pandas\core\internals\managers.py", line 352, in apply
    applied = getattr(b, f)(**kwargs)
  File "C:\Users\odejul00\.conda\envs\deepof\lib\site-packages\pandas\core\internals\blocks.py", line 526, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
  File "C:\Users\odejul00\.conda\envs\deepof\lib\site-packages\pandas\core\dtypes\astype.py", line 299, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
  File "C:\Users\odejul00\.conda\envs\deepof\lib\site-packages\pandas\core\dtypes\astype.py", line 230, in astype_array
    values = astype_nansafe(values, dtype, copy=copy)
  File "C:\Users\odejul00\.conda\envs\deepof\lib\site-packages\pandas\core\dtypes\astype.py", line 170, in astype_nansafe
    return arr.astype(dtype, copy=True)
ValueError: could not convert string to float: 'x'

```

I am attaching here one of my csv files. I couldn't figure out where the error is coming from.... do you know? 
[75799_1DLC_dlcrnetms5_SRDec16shuffle3_200000_el.csv](https://github.com/user-attachments/files/18141530/75799_1DLC_dlcrnetms5_SRDec16shuffle3_200000_el.csv)


Thank you very much for your help :) 
Best, 
Julia

**Comment by NoCreativeIdeaForGoodUserName** [comment]
Hi Julia,

There are two issues with your table: First you apparently accidentally included an additional row at the top of the table. Just remove it:

![Additional line](https://github.com/user-attachments/assets/32e73c5b-4e56-4997-b43d-192e36139930)

Next, the bodyparts "Left_fhip" and "Right_fhip" are missing the "f" (for "front" as in bigger labelling sets there is also a "bhip"

So if you remove that first row and rename "Left_hip" to "Left_fhip" and "Right_hip" to "Right_fhip" you should be able to create a project and run the supervised annotation to then create plots such as:

![image](https://github.com/user-attachments/assets/d5633e94-3ce6-43bd-b188-3ca0e11cfe64)

Note that the huddle annotator cannot be calculated due to a the 8-part scheme (it needs at least 11).

I hope this did help

Best regards,
Patrick

**Comment by juloder** [comment]
Cool! It worked out :) Thank you so much :)
